In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print("Corrected temperatures (°C):", corrected_temperature)

fahrenheit = (9/5) * corrected_temperature + 32
print("Temperatures (°F):", fahrenheit)

above_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", above_32)

count_above_32 = np.sum(corrected_temperature > 32)
print("Number of readings exceeding 32°C:", count_above_32)

Corrected temperatures (°C): [27 30 33 37 40 29 35 42]
Temperatures (°F): [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])


total_steps = np.sum(steps)
print("Total steps:", total_steps)


mean_steps = np.mean(steps)
print("Mean steps:", mean_steps)

print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

day_totals = np.sum(steps, axis=0)
print("Total steps for each day:", day_totals)

user_totals = np.sum(steps, axis=1)
print("Total steps for each user:", user_totals)


max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum value (user, day):", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum value (user, day): (np.int64(3), np.int64(2))


In [3]:

original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

subset = original[1:4]
print("Subset:", subset)

subset[0] = 999
print("After modifying subset:")
print("Original:", original)
print("Subset:", subset)

copied_array = original[1:4].copy()
copied_array[0] = 500
print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied array:", copied_array)

matrix = np.arange(1, 13).reshape(3, 4)
print("\n3 x 4 matrix:\n", matrix)


print("\nFirst row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:\n", matrix[0:2, 1:3])

flattened = matrix.flatten()
raveled = matrix.ravel()
print("\nUsing flatten():", flattened)
print("Using ravel():", raveled)

raveled[0] = 1000
print("\nAfter modifying ravel():")
print("Raveled array:", raveled)
print("Original matrix:\n", matrix)

flattened[1] = 2000
print("\nAfter modifying flatten():")
print("Flattened array:", flattened)
print("Original matrix:\n", matrix)


print("\nShape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4]
After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4]

3 x 4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
 [[2 3]
 [6 7]]

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel():
Raveled array: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten():
Flattened array: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Original matrix:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

Shape: (3, 4)
Number of dimensions: 2
Size: 12
Data type: int64


In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])


print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)


XT = X.T
print("\nX.T:\n", XT)

XTX = XT @ X
print("\nX.T @ X:\n", XTX)

XTX_inv = np.linalg.inv(XTX)
print("\nInverse of X.T @ X:\n", XTX_inv)

beta = XTX_inv @ XT @ y
print("\nOLS coefficients (beta):", beta)


print("\nCoefficient interpretation:")
print("The coefficients correspond to sleep hours, activity level, and stress level respectively.")
print("Each coefficient indicates the change in predicted assistance score associated with a one-unit change in that feature, while the other features are held constant.")


new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("\nPredicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients (beta): [-0.15921454  0.14083853 10.06302242]

Coefficient interpretation:
The coefficients correspond to sleep hours, activity level, and stress level respectively.
Each coefficient indicates the change in predicted assistance score associated with a one-unit change in that feature, while the other features are held constant.

Predicted assistance score: 75.27862544779117
