# Question 1


In [1]:
import numpy as np


In [4]:
arr = np.array([1,2,3,4,5])
addition = arr + 2
multiplication = arr * 3
division = arr / 2
print(addition)
print(multiplication)
print(division)


[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


# question 2


In [6]:
arr = np.array([1,2,3,4,5])
reverse = arr[::-1]
print(reverse)

[5 4 3 2 1]


In [8]:
def find_most_frequent(arr):
  vals, counts = np.unique(arr,return_counts= True)
  max_count = counts.max()
  most_frequent = vals[counts == max_count]
  for val in most_frequent:
   indices = np.where(arr == val )[0]
   print(f"Value: {val}, Indices: {indices}")

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
find_most_frequent(x)

Value: 1, Indices: [0 5 7 8 9]


#Question 3

In [9]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ans_a = arr[0,1]
print("a) 1st row, 2nd column:", ans_a)
ans_b = arr[2, 0]
print("b) 3rd row, 1st column:", ans_b)


a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


# Question 4

In [11]:
import numpy as np
Lakshita = np.linspace(10,100,25)
print("Array:\n", Lakshita)
print("Dimensions (ndim):", Lakshita.ndim)
print("Shape:", Lakshita.shape)
print("Total elements (size):", Lakshita.size)
print("Data type (dtype):", Lakshita.dtype)
print("Total bytes consumed (nbytes):", Lakshita.nbytes)


Lakshita_transposed = Lakshita.reshape(-1, 1)
print("\nTransposed using reshape(-1, 1):\n", Lakshita_transposed)

print("\nUsing .T attribute on 1D array:\n", Lakshita.T)

Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200

Transposed using reshape(-1, 1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using .T attribute on 1D array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


#Question 5


In [12]:
import numpy as np

ucs420_lakshita = np.array(
    [[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]]
)

print("Original Array:\n", ucs420_lakshita)
print("Mean:", np.mean(ucs420_lakshita))
print("Median:", np.median(ucs420_lakshita))
print("Max:", np.max(ucs420_lakshita))
print("Min:", np.min(ucs420_lakshita))
print("Unique Elements:", np.unique(ucs420_lakshita))

reshaped_ucs420_lakshita = ucs420_lakshita.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_lakshita)

resized_ucs420_lakshita = np.resize(ucs420_lakshita, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_lakshita)

Original Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
